[pytest]
addopts = -p no:cacheprovider
testpaths = tests
cache_dir = .tmp/pytest_cache
norecursedirs =
    .git
    .mypy_cache
    .pip-audit-cache
    .pythonlibs
    .testdata
    .tmp
    data
    pytest-cache-files-*
